export const API_CALL_REQUEST = 'API_CALL_REQUEST'
export const API_CALL_SUCCESS = 'API_CALL_SUCCESS'
export const API_CALL_FAIL = 'API_CALL_FAILURE'

export const API_CALL_NETWORKS = 'API_CALL_NETWORKS'
export const API_CALL_NETWORKS_SUCCESS = 'API_CALL_NETWORKS_SUCCESS'
export const API_CALL_NETWORKS_FAIL = 'API_CALL_NETWORKS_FAIL'

export const API_CALL_STATIONS = 'API_CALL_BICYCLES'
export const API_CALL_STATIONS_SUCCESS = 'API_CALL_BICYCLES_SUCCESS'
export const API_CALL_STATIONS_FAIL = 'API_CALL_BICYCLES_FAIL'